name: Publish
on: push
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: docker build & push
      run: |
        ./scripts/build_and_release.sh